(* This file is generated by AutoWp *)

Require Import ZArith Omega Lia.

Open Scope Z_scope.
Lemma lemma_0 :
	forall (b a : Z), a >= 0 /\ b >= 0 -> (a <= b -> b >= a /\ b >= b /\ (b = a \/ b = b)) /\ (not (a <= b) -> a >= a /\ a >= b /\ (a = a \/ a = b)).
Proof.
	intros. repeat split.
	- apply (Z.le_ge _ _ H0).
	- apply (Z.le_ge _ _ (Z.le_refl _)).
	- right; reflexivity.
	- apply (Z.le_ge _ _ (Z.le_refl _)).
	- apply Znot_lt_ge.
		intros Contr.
		apply (H0 (Z.lt_le_incl _ _ Contr)).
	- left; reflexivity.
Qed.
