(* This file is generated by AutoWp *)

Require Import ZArith Omega.

Open Scope Z_scope.
Lemma max :
	forall (b a : Z), a >= 0 /\ b >= 0 -> (a <= b -> b >= a /\ b >= b /\ (b = a \/ b = b)) /\ (not (a <= b) -> a >= a /\ a >= b /\ (a = a \/ a = b)).
Proof.
	try (intros; auto; omega).
Qed.
