(* This file is generated by AutoWp *)

Require Import ZArith Omega Lia.

Open Scope Z_scope.
Lemma div_eucl :
	forall (b a : Z), a >= 0 /\ b > 0 -> a = ((b * 0) + a) /\ (forall (r q : Z), r >= b /\ a = ((b * q) + r) -> a = ((b * (q + 1)) + (r - b))) /\ (not (a >= b) /\ a = ((b * 0) + a) -> a >= 0 /\ a <= b /\ a = ((b * 0) + a)).
Proof.
	intros; repeat split; lia.
Qed.
