(* This file is generated by AutoWp *)

Require Import ZArith Omega.

Open Scope Z_scope.
Lemma test :
	forall (x : Z), x >= 0 -> x >= 0 \/ 1 = 1 \/ (forall (x : Z), x > 0 \/ x >= 0 \/ 1 = 1 -> (x - 1) >= 0 \/ 1 = 1) \/ (not (x > 0) \/ x >= 0 \/ 1 = 1 -> x = 0).
Proof.
	try (intros; auto; omega).
Qed.
